"""empty message

Revision ID: 63f9d43e334b
Revises: 3c4aebaa2fdb
Create Date: 2020-12-25 15:59:07.200716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f9d43e334b'
down_revision = '3c4aebaa2fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'date')
    # ### end Alembic commands ###
